### ISSUE TITLE
 Template suggestion

### ISSUE THREAD

**Issue by guilherme-funchal** [AnonSolutions/indy-community-demo#18]
Hello, I rewrote the template aries/pageIncludes/profilecredentials.html to : 

======================================
```
{% load i18n %}
<h4>Credentials receives</h4>
{% for credential in credentials %}
<div class='newsfeed-posted-cont'>
        <div class='newsfeed-posted-event-opps-cont'>
                <br>
                <div>
                        <p><b>Schema : </b>{{ credential.schema_id }}</p>
                        <p><b>Cred Def : </b>{{ credential.cred_def_id }}</p>
                        <p><b>Referent : </b>{{ credential.referent }}</p>
			<p><b>Attrs : <b> {{ credential.attrs }}</p>
                        {% for x, y in credential.attrs.items %}
                                <p><b>{{ x }} : </b>
                                {{ y }}</p>
                        {% endfor %}

                </div>
        </div>
</div>
{% endfor %}

<div class='newsfeed-post-seperator'></div>
```
Who knows if it can be incorporated into the main code.

**Comment by ianco** [comment]
Can you submit this as a Pull Request?

It would be good to get this update into django-aries-framework as well.

**Comment by guilherme-funchal** [comment]
Don't use github, but I don't seem to have permission.

**Comment by ianco** [comment]
To send a Pull Request you:
- create your own fork of the repository (you have to have a github account)
- check in changes to your fork
- create a Pull Request to this repo
If you haven't done Pull Requests before there are probably tutorials online.  We need to do it this way to track authorship of any code changes.

**Comment by guilherme-funchal** [comment]
Ok, I'm going to prepare this today and place the pull request.

Thanks @ianco
